application: sozluk-214705
version: 1
runtime: php55
api_version: 1

handlers:
- url: /
  script: index.php

- url: /image_upload
  script: image_upload.php
  
# Serve php scripts.
- url: /(.+\.php)$
  script: \1

- url: /(.*\.(js))
  static_files: \1
  upload: (.*\.(js))
  application_readable: true

- url: /(.*\.(css))
  static_files: \1
  upload: (.*\.(css))
  application_readable: true
  
- url: /(.*\.(woff|woff2|tff|json))
  static_files: \1
  upload: (.*\.(woff|woff2|tff|json))
  application_readable: true
  
- url: /(.*\.(html|gif|png|jpg|ico|css|swf|xml))
  static_files: \1
  upload: (.*\.(html|gif|png|jpg|ico|css|swf|xml))
#  application_readable: true
  
